# Generated by Django 3.2.14 on 2022-08-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='people',
            old_name='name',
            new_name='names',
        ),
    ]
